spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-test
    username: root
    password: root
  application:
    name: user-service
server:
  port: ${port:9091}
mybatis:
  type-aliases-package: com.itheima.user.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
